spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    h2:
      jdbc-url: jdbc:h2:mem://localhost/~/tomas
      username: sa
      password:
      driverClassName: org.h2.Driver
    mysql:
      jdbc-url:
      username:
      password:
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG